
[platformio]
src_dir = main/
lib_dir = components/

[env]
; ↓platformio公式の espressif32 をバージョン指定で動かす場合はコレ
platform = espressif32@6.9.0   ; ←ESP-IDFv5.2.1 / Arduino v2.0.16(IDF4.4.7)

; ↓platformio公式の espressif32 最新を動かす場合はコレ (バージョン無指定)
; platform = espressif32

; ↓非公式の有志による espressif32 を動かす場合はコレ (releasesの中に複数のバージョン違いがあるのでURL記述を変えればバージョン指定できる)
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip

upload_speed = 1500000
monitor_speed = 115200
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
build_type = release
build_flags =
 -DCORE_DEBUG_LEVEL=0
 -DLOG_LOCAL_LEVEL=0
 -DAPP_LOG_LEVEL=0

[env:arduino_esp32]
board = esp32dev
framework = arduino

[env:arduino_esp32s3]
board = esp32-s3-devkitc-1
framework = arduino

[env:espidf_esp32]
board = esp32dev
framework = espidf

[env:espidf_esp32s3]
board = esp32-s3-devkitc-1
framework = espidf

; ↓M5GFXのサンプルをSDL使ってnativeビルドで動かす場合の設定例
[env:native]
platform = native
build_flags =
    -std=c++14 -xc++ -static -lSDL2 -lstdc++ -shared-libgcc -g
    -DM5GFX_BACK_COLOR=0x222222u               ; Color outside the frame image
    -DM5GFX_BOARD=board_t::board_M5StackCore2
    -DM5GFX_SHOW_FRAME
    -IC:/SDL2/include
    -LC:/SDL2/lib/x86
    -I"/usr/local/include/SDL2"                ; for intel mac homebrew SDL2
    -L"/usr/local/lib"                         ; for intel mac homebrew SDL2
    -I"${sysenv.HOMEBREW_PREFIX}/include/SDL2" ; for arm mac homebrew SDL2
    -L"${sysenv.HOMEBREW_PREFIX}/lib"          ; for arm mac homebrew SDL2

